- id: '1517693010922'
  alias: Adhan
  trigger:
  - platform: template
    value_template: '{{ states("sensor.dhuhr")  == states("sensor.time") }}'
  - platform: template
    value_template: '{{ states("sensor.asr")  == states("sensor.time") }}'
  - platform: template
    value_template: '{{ states("sensor.magrib")  == states("sensor.time") }}'
  - platform: template
    value_template: '{{ states("sensor.isha")  == states("sensor.time") }}'
  condition: []
  action:
  - alias: ''
    data:
      entity_id: media_player.living_room_speaker
      media_content_id: https://youtu.be/uiEGpnelJEA
      media_content_type: audio/youtube
    service: media_extractor.play_media
  - data:
      entity_id: media_player.living_room_speaker
      volume_level: '0.4'
    service: media_player.volume_set
  mode: single
- action:
  - data:
      entity_id: media_player.living_room_speaker
      media_content_id: https://s3.intahnet.co.uk/athan/fajr.mp3
      media_content_type: audio/mp3
    service: media_extractor.play_media
  - data:
      entity_id: media_player.living_room_speaker
      volume_level: '0.5'
    service: media_player.volume_set
  alias: Fajr Adhan
  condition: []
  id: '1517694139112'
  trigger:
  - platform: template
    value_template: '{{ states("sensor.fajr") == states("sensor.time") }}'
